### ISSUE TITLE
유튜브 영상다운, 얼굴인식, 원하는 사람 찾기 테스트

### ISSUE THREAD

**Issue by minhyeoky** [open-tube/open-tube#23]
[이 유튜브 동영상](https://www.youtube.com/watch?v=tPN9ScPQaow) 에서 아래 사람 찾기 결과 
![image](https://user-images.githubusercontent.com/12870549/62769791-a7a5ba00-bad4-11e9-8808-d6bad2af76db.png)
결과는 [테스트 노트북](https://nbviewer.jupyter.org/github/open-tube/open-tube/blob/face-test/190808%20%EC%98%A4%ED%94%88%ED%8A%9C%EB%B8%8C.ipynb)  에서 맨 아래만 보시면 됩니다.... 

#### 성능
그렇게 못 찾지는 않지만 유사도모델은 별로 검증된 모델도 아니고 애초에 서양인으로 학습했을 거라 좋지 않네요.

#### 속도
모델보다도 전처리 및 영상 불러오는 시간이 꽤 됩니다..
최적화할게 남아서 좀 더 줄일 수도 있고 병렬+스트리밍처리로 더 줄일수는 있는데 지금은 15분짜리 영상하는데에 5분넘게 걸립니다. (720p, 30fps기준)

#### 그래서?
솔직히 어디에 쓸지모르겠고 뭐 이런거 가능하다 정도. 
유사도쪽 새로 학습할 수는 있을 것 같은데 남은 시간이 적기 때문에 하는 건 좋지 않을 것 같습니다.
얼굴인식 모델은 쓸만하기 때문에 활용해서 익명화라던가 인물 타임라인이라던가는 해줄 수 있을 것 같습니다...

**Comment by lenon461** [comment]
나은찾기테스트인가요?

**Comment by minhyeoky** [comment]
> 나은찾기테스트인가요?

네 ㅎㅎ
