### ISSUE TITLE
:fire: :fire::fire::fire::fire:서버터짐:fire::fire::fire::fire::fire::fire:

### ISSUE THREAD

**Issue by minhyeoky** [open-tube/open-tube#47]
## 버그 내용
아코디언서버 또 터짐

## 재현 과정
ssh / accordion / db port

**Comment by minhyeoky** [comment]
서버 재설치중

**Comment by minhyeoky** [comment]
[wiki](https://github.com/open-tube/open-tube/wiki/%F0%9F%93%9D-Accordion-%EC%9E%AC%EC%84%A4%EC%B9%98-%EB%B0%8F-%EB%B3%80%EA%B2%BD%EC%82%AC%ED%95%AD-%EB%AC%B8%EC%84%9C%ED%99%94)

**Comment by taeuk-gang** [comment]
## 터진 서버 분석

### 시스템 구동 서비스 중 `nfs` 서비스가 부팅시 정상 작동하지 않음, 그러므로 마운트도 잇따라...
![image](https://user-images.githubusercontent.com/26294469/62963462-06a06180-be3c-11e9-922c-cb962d8005c0.png)

### 둘 다 명령어 고칠 수 있지만, 재부팅하면 똑같이 무한 부팅 발생
![image](https://user-images.githubusercontent.com/26294469/62964803-b4147480-be3e-11e9-86ec-a3a865233aac.png)


### 터진 서버의 아코디언 상태
![image](https://user-images.githubusercontent.com/26294469/62972298-ac5ccc00-be4e-11e9-97ca-5e0c8478e488.png)
