### ISSUE TITLE
history 및 Download & 영상 분석 API

### ISSUE THREAD

**Issue by minhyeoky** [open-tube/open-tube#53]
## 목표

서버에서 api 배포

## 진행 사항

(Swagger 참고)

- [x] History 
- [x] Download

## 다음 목표

감성분석, 키워드와 통합

### TEST:
19.08.17
32600 포트에서 테스트가능

### history:

![image](https://user-images.githubusercontent.com/12870549/63199162-f2689880-c0b7-11e9-9fd9-d6aa0fd9c9b3.png)

response: 201

**table**: 
![image](https://user-images.githubusercontent.com/12870549/63201983-8b9cac80-c0c2-11e9-8af1-3111dfb433e9.png)

### Download: (영상분석 endpoint)

![image](https://user-images.githubusercontent.com/12870549/63199316-70c53a80-c0b8-11e9-82c0-58d9864c902a.png)

**response:**

```python
{
	'status': # ('wait', 'processing', 'complete'), 중 하나. 
	'time_line': # 만약 status가 'complete'라면, 리턴
		{
		'face_id': [
		{
		time(sec): [xmin, xmax, ymin, ymax] # face box
		}, ...
    ]
    }
}
```

```text
face 사진의 위치: /mnt/ssd/server/faces/${uid}/${vid}/${face_id}.jpg
동영상의 위치: /mnt/ssd/server/downloads/${동영상의제목}.mp4
```
### examples
**테스트 영상**
https://www.youtube.com/watch?v=UjvHz67oQ8A
![image](https://user-images.githubusercontent.com/12870549/63201916-3a8cb880-c0c2-11e9-8868-9ac35e013524.png)

**api response**
![image](https://user-images.githubusercontent.com/12870549/63201883-0f09ce00-c0c2-11e9-84d6-e0fe46961141.png)

**faces** (크기: 128x128x3) 
![image](https://user-images.githubusercontent.com/12870549/63201896-2052da80-c0c2-11e9-840e-7fa3e7612b0a.png)

**Comment by taeuk-gang** [comment]
![image](https://user-images.githubusercontent.com/26294469/63243950-ff8fae00-c296-11e9-9dfe-b08a2377495f.png)

이거 화면 점 4개 좌표?

화면 크기 기준 몇임?

**Comment by minhyeoky** [comment]
아 원본영상 512x512 로 리사이즈 한 것 기준인데.

원래 원본영상에 맞게 바꿀게

**Comment by taeuk-gang** [comment]
항상 영상 크기가 동일하지 않음?

그것보다 점 4개 좌표임?

**Comment by minhyeoky** [comment]
(xmin, xmax, ymin, ymax) 일거고 영상크기는 내가 1280x720을 받아서 512x512로 작업을 함

그래서 좌표도 지금은 512x512로 주는데

원본에 맞게 스케일해서줌 기달

**Comment by taeuk-gang** [comment]
으음 조금 더 정확히 궁금한 것은 영상크기가 항상 일정 하지 않는가? (Y/N) 이고,
나한테 점4개가 아니라, 왼쪽 윗점과 width, height을 주기로 하지 않았나 궁금해서 물어봄

**Comment by minhyeoky** [comment]
> 으음 조금 더 정확히 궁금한 것은 영상크기가 항상 일정 하지 않는가? (Y/N) 이고,
> 나한테 점4개가 아니라, 왼쪽 윗점과 width, height을 주기로 하지 않았나 궁금해서 물어봄

1. 항상 화질 720p로 받기 때문에 동일 할 것임
2. 까먹음 ㄱㄷ

**Comment by taeuk-gang** [comment]
시간 주기가 그렇게 세밀하지 않아서, 영상 재생하면서 박스 이동은 어렵겠는데?

정지 상태에서만 보여주는 걸로 해?

**Comment by minhyeoky** [comment]
> 시간 주기가 그렇게 세밀하지 않아서, 영상 재생하면서 박스 이동은 어렵겠는데?

초단위로 차이를 보정하면 될거같은데.

// (2초박스 - 1초박스) / fps 를 앞에꺼에 더하면 프레임별로 구할수있을듯

**Comment by minhyeoky** [comment]
뭐 굳이 재생까지 안해도 되지

**Comment by taeuk-gang** [comment]
음, 그런데 내가 사용자에게 보여줄때는 항상 영상 전체크기 같진 않거든? (사용자 화면 상대크기에 따라 변함)

그래서 별도 % 계산 처리를 해야할 수 도 있는데, 다시 물어봐서 미안하긴한데 동영상 전체크기는 항상 일정해? 계산해야되서 다시 재확인 점

**Comment by minhyeoky** [comment]
확인하고 댓글담 ㄱㄷ

**Comment by taeuk-gang** [comment]
> 확인하고 댓글담 ㄱㄷ

ㅇㅋㅇㅋ 기다림

![image](https://user-images.githubusercontent.com/26294469/63244918-aa08d080-c299-11e9-9b9e-02060680db3f.png)
현재 수정 중이라서, API 미동작인건가

**Comment by minhyeoky** [comment]
> > 확인하고 댓글담 ㄱㄷ
> 
> ㅇㅋㅇㅋ 기다림
> 
> ![image](https://user-images.githubusercontent.com/26294469/63244918-aa08d080-c299-11e9-9b9e-02060680db3f.png)
> 현재 수정 중이라서, API 미동작인건가

로컬에서해서 상관없을텐데 아직도 안됨?

**Comment by taeuk-gang** [comment]
> 로컬에서해서 상관없을텐데 아직도 안됨?

잠깐 렉이였던 듯, 자주 발생하면 이야기 할게

**Comment by taeuk-gang** [comment]
음... 얼굴 사진 볼륨 500GB정도로 배정할게

**Comment by minhyeoky** [comment]
> 음... 얼굴 사진 볼륨 500GB정도로 배정할게

이미내가 ssd 500기가 끌어다 쓰고있지않음?

**Comment by taeuk-gang** [comment]
> 이미내가 ssd 500기가 끌어다 쓰고있지않음?

그거 너무 포괄적으로 폴더 잡아뒀던데? server 폴더 통채로 잡아둬서, 내 서버까지 포함되어있음

**Comment by minhyeoky** [comment]
> > 이미내가 ssd 500기가 끌어다 쓰고있지않음?
> 
> 그거 너무 포괄적으로 폴더 잡아뒀던데? server 폴더 통채로 잡아둬서, 내 서버까지 포함되어있음

아 영상포함임 /server/downloads에 영상들어가있음 그게 크지

**Comment by taeuk-gang** [comment]
그거 2개 폴더 별도 볼륨 설정해야 받아야 할 듯.

그 외 서버 폴더에 model이랑 web-server는 필요없을 뿐더러, 보안적으로 좋아보이진 않네

**Comment by minhyeoky** [comment]
> 으음 조금 더 정확히 궁금한 것은 영상크기가 항상 일정 하지 않는가? (Y/N) 이고,
> 나한테 점4개가 아니라, 왼쪽 윗점과 width, height을 주기로 하지 않았나 궁금해서 물어봄

1. Y 1280x720
2. 바꿈 빌드중
(xmin, ymax, width, height)
