### ISSUE TITLE
레포트 페이지 디자인 및 내용물 구현

### ISSUE THREAD

**Issue by taeuk-gang** [open-tube/open-tube#58]
## 목표
레포트 페이지 일관성 있는 디자인 형식 구성

## 진행 사항

- [x] 참고 디자인 항목 조사 [(참고 1)](https://dribbble.com/shots/3151132-Aspaway/attachments/668383) [(참고 2)](http://www.awesomescreenshot.com/image/247955/fcedf17ecd0322d5a6e1870fa5d87295) [(참고 3)](https://dribbble.com/shots/5731328-Card-Analytics-Dashboard/attachments)
- [x] 목표 디자인 구현, 일관성 및 짜임새 있게 구성
- [x] 얼굴 인식 API 레포트 형식에 맞게 추가

## 다음 목표
- 댓글 감성분석 및 키워드분석 API 추가

**Comment by minhyeoky** [comment]
(참고 1) 에 색상 맵만 유튜브 특유의 흰빨/ 검빨로 바꾸면 좋을 것 같읍니다.

**Comment by taeuk-gang** [comment]
> (참고 1) 에 색상 맵만 유튜브 특유의 흰빨/ 검빨로 바꾸면 좋을 것 같읍니다.

참고 디자인 좀 더 줘봐

**Comment by minhyeoky** [comment]
> > (참고 1) 에 색상 맵만 유튜브 특유의 흰빨/ 검빨로 바꾸면 좋을 것 같읍니다.
> 
> 참고 디자인 좀 더 줘봐

https://wnddpd01.github.io/lol

https://www.youtube.com/?hl=ko&gl=KR
